model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelTorchTuneCheckpointer #torchtune.utils.FullModelMetaCheckpointer

  # directory with the checkpoint files
  # this should match the output_dir specified during
  # fine-tuning
  checkpoint_dir: /teamspace/studios/this_studio/llama3-8b-hf/

  # checkpoint files for the fine-tuned model. These will be logged
  # at the end of your fine-tune
  checkpoint_files: [
    /teamspace/studios/this_studio/llama3-8b-hf/meta_model_0-4w.pt
    # /teamspace/studios/this_studio/llama3-8b-hf/meta_model_0.pt,
  ]
  adapter_checkpoint: /teamspace/studios/this_studio/llama3-8b-hf/adapter_0.pt

  output_dir: /teamspace/studios/this_studio/llama3-8b-hf/
  model_type: LLAMA3

# Make sure to update the tokenizer path to the right
# checkpoint directory as well
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /teamspace/studios/this_studio/llama3-8b-hf/original/tokenizer.model
  
device: cuda # cpu
dtype: bfp16 #bf16

seed: 1234
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

# quantizer: null
quantizer:
  _component_: torchtune.utils.quantization.Int4WeightOnlyQuantizer
  groupsize: 256


